language: generic

sudo: required

services:
- docker

script:
- docker login -u tomfitzhenry -p $BINTRAY_API_KEY -e tom@tom-fitzhenry.me.uk certificate-transparency-watch-docker-ct-watch-registry.bintray.io
- docker build -t certificate-transparency-watch-docker-ct-watch-registry.bintray.io/ct-watch-nginx .
- docker push certificate-transparency-watch-docker-ct-watch-registry.bintray.io/ct-watch-nginx

env:
  global:
    secure: lRR1wv/wvf81LBNQRGdqyfizglYNbrcxgGof8H5LZTkqLj9jayEcAbZ5wRcpRwJVat5TkPqKrvITZxGh5wB5ho9JFwrkEbQwXjmO3kp1yWWHk5AGbC5CuIVh0W6YCKFMiV176dgyaW6evUXQaN9Mozad310IAysY+RuAQE1iw4OxlNnG3/eEz72pKo4LqOtchuWFYpu0OukB7J2wsHC2Gyja0HKEZTDD/El23EC04Ki5X5W0hZfidqZXhHyatNZdbNCzQfbgENnEAYtZlCqvALNo4PlbgN1yLWSu6g/IxDfAEvxRkLnOvkW1EX872jyR5MfXW+t2rhsiguU6EqEhXsFtfGL8JcKcQMsvNLH0T0ytDwGIN7fXXvicmVUOifYrPYuuQh7soB66Ldk9UeWrAiW8PLwEjYelFEHo151f/9ggYzMXcZA8rWhfDLCPMtuDraa9TjW3LGeE04uGgqtWtynsEdex7WC003Btyy3Ki52E+ffOmfclHRh/w8qtYwPUiNxMOuJAganpasQsGZhXkW5qqx8fkZ7iZLyduI8DCMsvZFHuIH8e8Iawtqb4GrSc+lyAQNLI0zcl+gOneU/Ln5we4u7WhsXjoSWw3dY6TFU3uN6A6nPXUmCZVqYvEAA9jCPRCCVrIb6B0IzTkqVPL4WqoHIQHbIo16wf1YbTS5k=
